# Generated by Django 5.2.4 on 2025-07-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_githubrun_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rustdesdevice',
            name='ip',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='IP Address'),
        ),
    ]
