# Generated by Django 5.2.4 on 2025-07-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_rustdesdevice_ip_alter_rustdeskpeer_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrun',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
