# Generated by Django 5.2.4 on 2025-07-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_githubrun_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connlog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
